server:
  port: 8081


spring: #springboot的配置
  datasource: #定义数据源
    #127.0.0.1为本机测试的ip，3306是mysql的端口号。serverTimezone是定义时区，照抄就好，mysql高版本需要定义这些东西
    #useSSL也是某些高版本mysql需要问有没有用SSL连接
    url: jdbc:mysql://${MYSQL_IP}:${MYSQL_PORT}/zcjdata?useUnicode=true&characterEncoding=utf-8
    username: root  #数据库用户名，root为管理员
    password: zcj123 #该数据库用户的密码

mybatis:  #mybatyis的配置

  typeAliasesPackage: com.zcj.dao
  mapper-locations: classpath:mapper/*.xml
  configLocation: classpath:/mybatis-config.xml
