server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://${MYSQL_IP}:${MYSQL_PORT}/zcjdata?useUnicode=true&characterEncoding=utf-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

mybatis:

  typeAliasesPackage: com.zcj.dao
  mapper-locations: classpath:mapper/*.xml
  configLocation: classpath:/mybatis-config.xml
